#!/bin/sh
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
entries="$here/entries"
tmp="$here/README.md.tmp"

{
    printf '%s\n\n' '# Polynomial and variety catalog'
    printf '%s\n\n' '<!-- GENERATED by generate-readme.sh. Edit entry files or the generator, not catalog rows here. -->'
    printf '%s\n\n' 'Exhaustive target: every explicit polynomial and every explicit variety/scheme/ideal/system in *Computations in Algebraic Geometry with Macaulay 2*.'
    printf '%s\n\n' 'Mathematical display uses `×` when an explicit multiplication sign is needed. Exact Macaulay2 syntax is kept separately.'
    printf '%s\n\n' 'A missing render is shown as **render pending** so coverage gaps remain visible.'

    find "$entries" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort |
    while IFS= read -r d
    do
        id=${d##*/}
        kind=$(cat "$d/kind.txt")
        equation=$(cat "$d/equation.txt")

        printf '## %s\n\n' "$equation"
        printf -- '- ID: `%s`\n' "$id"
        printf -- '- kind: %s\n' "$kind"
        printf -- '- [source](entries/%s/source.txt) · [why](entries/%s/why.md)' "$id" "$id"
        if [ -f "$d/macaulay2.txt" ]; then
            printf ' · [Macaulay2](entries/%s/macaulay2.txt)' "$id"
        fi
        if [ -f "$d/components.txt" ]; then
            printf ' · [components](entries/%s/components.txt)' "$id"
        fi
        printf '\n\n'

        if [ -f "$d/render.png" ]; then
            printf '![%s](entries/%s/render.png)\n\n' "$equation" "$id"
        elif [ -f "$d/render.gif" ]; then
            printf '![%s](entries/%s/render.gif)\n\n' "$equation" "$id"
        elif [ -f "$d/render.mp4" ]; then
            printf '[SURFER render](entries/%s/render.mp4)\n\n' "$id"
        else
            printf '%s\n\n' '**render pending**'
        fi
    done
} > "$tmp"

mv "$tmp" "$here/README.md"
