#!/bin/sh
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
tmp="$here/README.md.tmp"

"$here/validate.sh"

{
    printf '%s\n\n' '# Polynomial and variety catalog'
    printf '%s\n\n' '<!-- GENERATED by generate-readme.sh. Edit catalog files or the generator, not catalog rows here. -->'
    printf '%s\n\n' 'Exhaustive target: every explicit polynomial and every explicit variety/scheme/ideal/system in *Computations in Algebraic Geometry with Macaulay 2*.'
    printf '%s\n\n' 'Each polynomial has exactly three siblings: one primary render slot, provenance, and why-it-is-mentioned.'
    printf '%s\n\n' 'A polynomial is not the same object as a variety; composite varieties appear separately below.'

    find "$here" -maxdepth 1 -type f -name '*.source.txt' -print | LC_ALL=C sort |
    while IFS= read -r source
    do
        base=${source%.source.txt}
        name=${base##*/}
        display=$(sed -n 's/^Display: //p' "$source" | head -n 1)
        [ -n "$display" ] || display="$name"
        label=$(sed -n 's/^Catalog label: //p' "$source" | head -n 1)
        [ -n "$label" ] || label="$display"

        printf '## %s\n\n' "$label"
        printf -- '- [source](<%s.source.txt>) · [why](<%s.why.txt>)\n\n' "$name" "$name"

        if [ -f "$base.png" ]; then
            printf '![%s](<%s.png>)\n\n' "$label" "$name"
        elif [ -f "$base.gif" ]; then
            printf '![%s](<%s.gif>)\n\n' "$label" "$name"
        elif [ -f "$base.mp4" ]; then
            printf '[SURFER rotation](<%s.mp4>)\n\n' "$name"
        elif grep -q '^status: unavailable$' "$base.render.txt"; then
            reason=$(sed -n 's/^reason: //p' "$base.render.txt" | head -n 1)
            printf '**SURFER unavailable:** %s\n\n' "$reason"
        else
            formula=$(sed -n 's/^SURFER: //p' "$source" | head -n 1)
            printf '**SURFER render pending:** `%s`\n\n' "$formula"
        fi
    done

    printf '%s\n\n' '## Composite varieties, schemes, ideals, and systems'

    find "$here" -maxdepth 1 -type f -name '*.variety.txt' -print | LC_ALL=C sort |
    while IFS= read -r record
    do
        file=${record##*/}
        name=${file%.variety.txt}
        printf -- '- [%s](<%s>)\n' "$name" "$file"
    done
    printf '\n'
} > "$tmp"

mv "$tmp" "$here/README.md"
